apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-order-service
  namespace: {{.Release.Namespace}}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /order/$2
    cert-manager.io/issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - {{.Values.dnsName}}
      secretName: {{.Values.tlsCertSecretName}}
  rules:
    - host: {{.Values.dnsName}}
      http:
        paths:
          - path: /order(/|$)(.*)
            pathType: Prefix
            backend:
              service: 
                name: order-service
                port: 
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-order-service-menu
  namespace: {{.Release.Namespace}}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /menuitem/$2
    cert-manager.io/issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - {{.Values.dnsName}}
      secretName: {{.Values.tlsCertSecretName}}
  rules:
    - host: {{.Values.dnsName}}
      http:
        paths:
          - path: /menuitem(/|$)(.*)
            pathType: Prefix
            backend:
              service: 
                name: order-service
                port: 
                  number: 80