kind: Service
apiVersion: v1
metadata:
  name: receipt-generation-service
  namespace: {{.Release.Namespace}}
  labels:
    app: receipt-generation-service
spec:
  selector:
    app: receipt-generation-service
  ports:
    - protocol: TCP
      port: {{.Values.service.port}}
      targetPort: {{.Values.service.targetPort}}
  type: ClusterIP
