dnsName: dapr-workshop.vigilantes.dev
tlsCertSecretName: vigilantes-dev-tls

service:
  port: 80
  targetPort: 80

deployment:
  replicas: 1
  image:
    registry: ghcr.io
    name: azurevigilantes/dapr-workshop/csharp/order-service
    tag: latest
    pullPolicy: Always
  containerPort: 80
  aadPodIdentityBinding: vigilantes-aks-msi
