apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: orders
  namespace: default
spec:
  type: bindings.cron
  version: v1
  metadata:
  - name: schedule
    value: "15 * * * * *"
scopes:
- virtual-barista
