apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    secretKeyRef:
      name: redisHost
      key: redisHost
  - name: redisPassword
    value: ""
scopes:
- loyalty-service
- order-service
- make-line-service
- receipt-generation-service
auth:
  secretStore: azurekeyvault