apiVersion: apps/v1
kind: Deployment
metadata:
  name: loyalty-service
  namespace: {{.Release.Namespace}}
  labels:
    app: loyalty-service
spec:
  replicas: {{.Values.deployment.replicas}}
  selector:
    matchLabels:
      app: loyalty-service
  template:
    metadata:
      labels:
        app: loyalty-service
        {{- if .Values.deployment.aadPodIdentityBinding }}
        aadpodidbinding: {{ .Values.deployment.aadPodIdentityBinding }}
        {{- end }}
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "loyalty-service"
        dapr.io/app-port: "{{.Values.deployment.containerPort}}"
        dapr.io/config: "tracing"
    spec:
      containers:
        - name: loyalty-service
          image: "{{.Values.deployment.image.registry}}/{{.Values.deployment.image.name}}:{{.Values.deployment.image.tag}}"
          ports:
            - containerPort: {{.Values.deployment.containerPort}}
          imagePullPolicy: {{.Values.deployment.image.pullPolicy}}
