apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-ui
  namespace: {{.Release.Namespace}}
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - {{.Values.dnsName}}
      secretName: {{.Values.tlsCertSecretName}}
  rules:
    - host: {{.Values.dnsName}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: 
                name: ui
                port: 
                  number: 80